### Setup

In [28]:
import torch as t
import torch.nn.functional as F 
from torch.autograd import grad
from sklearn import linear_model

from dataclasses import dataclass

from rich import print

In [ ]:
# For consistent results
t.manual_seed(123)

In [2]:
device = t.device("cuda" if t.cuda.is_available() else "cpu")

In [3]:
device

device(type='cuda')

### Loading Data
- [ ] Look for basic datasets (or use toy datasets first)
- [ ] Turn this into a Torch Dataset
- [ ] Access Torch Dataset via Dataloaders
- [ ] Do everything similarly using sklearn

### Logistic Regression using PyTorch

##### Trying out matmul with grad

In [24]:
x = t.randn(10, requires_grad=True, device=device)
weights = t.rand(10, requires_grad=True, device=device)
# small positive initialization
bias = t.ones(10, device=device) * 0.1

print(f"Tensor pertaining to input: \n {x}")
print(f"Tensor pertaining to weights: \n {weights}")
print(f"Tensor pertaining to bias: \n {bias}")



Tensor pertaining to input: 
 tensor([ 1.5190, -0.5678, -0.2385, -0.6783,  0.5204, -0.9234,  1.4720, -0.5877,
        -0.3210,  0.2898], device='cuda:0', requires_grad=True)

Tensor pertaining to weights: 
 tensor([0.3764, 0.3801, 0.2915, 0.5394, 0.8064, 0.8145, 0.3347, 0.2936, 0.3256,
        0.9996], device='cuda:0', requires_grad=True)

Tensor pertaining to bias: 
 tensor([0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
        0.1000], device='cuda:0')

In [30]:
z = x @ weights + bias
activated_z = t.sigmoid(z)
# loss = F.binary_cross_entropy()
# compute grad

print(z)
print(activated_z)

tensor([0.1935, 0.1935, 0.1935, 0.1935, 0.1935, 0.1935, 0.1935, 0.1935, 0.1935,
        0.1935], device='cuda:0', grad_fn=<AddBackward0>)

tensor([0.5482, 0.5482, 0.5482, 0.5482, 0.5482, 0.5482, 0.5482, 0.5482, 0.5482,
        0.5482], device='cuda:0', grad_fn=<SigmoidBackward0>)

##### Data

In [ ]:
# Instantiate Dataset and Dataloader

##### Model

In [47]:
@dataclass
class Config:
    batch: int = 5
    input_dim: int = 10
    output_dim: int = 1
    device: t.device = device

cfg = Config()

print(f"The batch size is: {cfg.batch}")
print(f"The input dim is: {cfg.input_dim}")

The batch size is: 5

The input dim is: 10

In [50]:

class LogisticRegression(t.nn.Module):
    '''
        Simple LogisticRegression using PyTorch 
    '''
    def __init__(self, cfg: Config):
        super().__init__()
        self.cfg = cfg
        self.linear = t.nn.Linear(self.cfg.input_dim, self.cfg.output_dim, device=self.cfg.device)

    def forward(self, x):
        logits = self.linear(x)
        probs = t.sigmoid(logits)
        
        return probs


x = t.randn((cfg.batch, cfg.input_dim), device=cfg.device)
model = LogisticRegression(cfg)

with t.inference_mode():
    output = model(x)
    print(output)
    print(output.device)


tensor([[0.3391],
        [0.6843],
        [0.6086],
        [0.6359],
        [0.3607]], device='cuda:0')

cuda:0

##### Training Loop

In [ ]:
# PSEUDO PSEUDO CODE
# loop through epochs
# loop through batches of dataloader
# get outputs, get loss, zero grad, backprop, optimizer step

### Logistic Regression using Sklearn