# Tensor Operations on PyTorch and Einops
---
Just comparing syntactical differences between vanilla Torch operations vs. Einops. Additionally, I used different options to perform matmul for a minimal Perceptron implementation

### Setup

In [1]:
import torch as t
import einops as eo
import numpy as np
from dataclasses import dataclass

device = t.device("cuda" if t.cuda.is_available() else "cpu")

In [2]:
t.__version__

'2.1.0+cu121'

In [3]:
device

device(type='cuda')

### Minimal Benchmarking
---
Comparing differences between using Tensor methods vs. @. According to online resources, @ operates faster especially for larger tensors.

In [4]:
A = t.randn(10)
B = t.randn(10)
C = t.randn((5, 10))

print(A @ B)
print(A.dot(B))
print(C @ A)
print(C.matmul(A))


tensor(-3.5933)
tensor(-3.5933)
tensor([-1.0633,  3.0227, -0.0661, -1.8092, -5.4111])
tensor([-1.0633,  3.0227, -0.0661, -1.8092, -5.4111])


In [5]:
%timeit A.dot(B)

2.73 µs ± 169 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
%timeit A @ B

3.46 µs ± 248 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Testing Einops

In [7]:
fake_image = t.randint(0, 255, (96, 96, 3), device=device)

In [8]:
fake_np_img = np.random.randint(255, size=(64, 64, 3))

In [14]:
eo.rearrange(fake_np_img, 'h w c -> w h c')

(64, 64, 3)

In [15]:
eo.rearrange(fake_np_img, 'h w c -> (h w c)').shape

(12288,)

: 

### Minimal Perceptron Implementation

In [10]:
@dataclass
class Config:
    batch_size: int = 150
    dim: int = 50
    bias: int = 0

In [11]:
cfg = Config()

t.rand(cfg.dim)

tensor([1.1617e-01, 2.9531e-01, 8.1326e-01, 5.2690e-01, 4.7365e-01, 6.9079e-01,
        4.7149e-01, 2.1553e-01, 6.7955e-01, 9.4254e-01, 6.1680e-01, 8.3811e-01,
        8.3989e-01, 3.6920e-01, 5.6553e-01, 8.4530e-01, 2.1171e-01, 3.0843e-01,
        1.7100e-01, 3.0391e-01, 8.4071e-01, 6.1277e-01, 9.4606e-01, 9.4990e-01,
        9.7225e-01, 9.7965e-01, 5.6676e-01, 9.8509e-02, 4.5395e-01, 9.0738e-02,
        1.9128e-01, 4.3274e-01, 6.5174e-01, 8.4323e-04, 1.8355e-01, 3.4983e-01,
        2.6994e-01, 8.1129e-01, 8.4119e-01, 3.5221e-01, 1.3352e-01, 1.4109e-01,
        2.0150e-01, 1.4824e-01, 9.8783e-01, 5.3288e-01, 3.1903e-02, 2.0534e-01,
        4.2547e-01, 9.7368e-01])

In [12]:
class Perceptron:
    def __init__(self, cfg: Config):
        self.cfg = cfg
        self.dim = self.cfg.dim
        self.weights = t.rand(self.dim)
        self.bias = self.cfg.bias
    
    def forward(self, x: t.Tensor):
        # Still need to add the threshold function
        return x @ self.weights + self.bias

    def update(self):
        # piece-wise that works directly on error
        pass


model = Perceptron(cfg)

In [13]:
x = t.rand((cfg.batch_size, cfg.dim))

model.forward(x).shape

torch.Size([150])