#### I want to see the differences in:
* Speed
* Verbosity

when computing with:
* For loops
* PyTorch Tensors
* Einops



### Setup

In [9]:
import torch as t
from dataclasses import dataclass

device = t.device("cuda" if t.cuda.is_available() else "cpu")

In [5]:
t.__version__

'2.1.0+cu121'

In [2]:
device

device(type='cuda')

### Minimal Benchmarking
---
Comparing differences between using Tensor methods vs. @. According to online resources, @ operates faster especially for larger tensors.

In [4]:
A = t.randn(10)
B = t.randn(10)
C = t.randn((5, 10))

print(A @ B)
print(A.dot(B))
print(C @ A)
print(C.matmul(A))


tensor(0.0607)
tensor(0.0607)
tensor([-0.1744,  7.5032, -4.4844,  4.0740,  0.0352])
tensor([-0.1744,  7.5032, -4.4844,  4.0740,  0.0352])


In [5]:
%timeit A.dot(B)

2.06 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
%timeit A @ B

2.39 µs ± 91.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Minimal Perceptron Implementation

In [10]:
@dataclass
class Config:
    batch_size: int = 150
    dim: int = 50
    bias: int = 0

In [17]:
cfg = Config()

t.rand(cfg.dim)

tensor([0.7161, 0.8991, 0.1289, 0.9035, 0.7489, 0.6061, 0.9852, 0.6685, 0.6255,
        0.9706, 0.8243, 0.1047, 0.9029, 0.5215, 0.5192, 0.9593, 0.2049, 0.3035,
        0.1134, 0.7873, 0.4234, 0.6672, 0.9633, 0.6437, 0.6667, 0.6866, 0.3409,
        0.6675, 0.1333, 0.7062, 0.9062, 0.0141, 0.3397, 0.7208, 0.8370, 0.8042,
        0.8269, 0.0795, 0.0271, 0.3421, 0.2195, 0.8257, 0.6976, 0.7046, 0.9519,
        0.7407, 0.7738, 0.7141, 0.3958, 0.6465])

In [25]:
class Perceptron:
    def __init__(self, cfg: Config):
        self.cfg = cfg
        self.dim = self.cfg.dim
        self.weights = t.rand(self.dim)
        self.bias = self.cfg.bias
    
    def forward(self, x: t.Tensor):
        return x @ self.weights + self.bias

    def update(self):
        pass


model = Perceptron(cfg)

In [27]:
x = t.rand((cfg.batch_size, cfg.dim))

model.forward(x).shape

torch.Size([150])